const MAX_DISTANCE_THRESHOLD = 5;
const PER_MINUTE_FARE = 2;
const PER_KM_FARE = 6.5;
const BASE_FARE = 50;
const SERVICE_TAX = 0.2;
const ZERO_AVAIALBLE_DRIVERS = 0;
const FIXED_DECIMAL_PLACES = 2;
const TOP_N_DRIVERS = 5;
const MATH_SQUARE = 2

const INVALID_RIDE = "INVALID_RIDE";
const RIDE_STARTED = "RIDE_STARTED";
const RIDE_STOPPED = "RIDE_STOPPED";
const NO_DRIVERS_AVAILABLE = "NO_DRIVERS_AVAILABLE";
const DRIVERS_MATCHED = "DRIVERS_MATCHED";
const RIDE_NOT_COMPLETED = "RIDE_NOT_COMPLETED";
const BILL = "BILL";
const DRIVERS = "DRIVERS";
const RIDERS = "RIDERS";
const MATCH = "MATCH";
const START_RIDE = "START_RIDE";

module.exports = {
    MAX_DISTANCE_THRESHOLD,
    PER_KM_FARE,
    PER_MINUTE_FARE,
    BASE_FARE,
    ZERO_AVAIALBLE_DRIVERS,
    FIXED_DECIMAL_PLACES,
    TOP_N_DRIVERS,
    SERVICE_TAX,
    INVALID_RIDE,
    RIDE_STARTED,
    RIDE_NOT_COMPLETED,
    NO_DRIVERS_AVAILABLE,
    DRIVERS_MATCHED,
    MATH_SQUARE,
    BILL,
    RIDE_STOPPED,
    DRIVERS,
    RIDERS,
    MATCH,
    START_RIDE
}